home734787902.1and1-data.host:
  stage: staging
  deploy_path: ~/clickandbuilds/csabacenter/stage
  user: u93352011
  webroot: public
  writable_mode: chmod
  multiplexing: false
  typo3_context: Production/Staging