p524924.webspaceconfig.de:
  stage: staging
  deploy_path: ~/html/csabacenter
  user: p524924
  webroot: public
  writable_mode: chmod
  multiplexing: false
  typo3_context: Production/Staging

p526584.webspaceconfig.de:
  stage: production
  deploy_path: ~/html/csabacenter
  user: p526584
  webroot: public
  writable_mode: chmod
  multiplexing: false
  typo3_context: Production/Live
